### ISSUE TITLE
Linked Servers

### ISSUE THREAD

**Issue by jnpetersen** [dmuegge/ddb-sql-toolkit#1]
Are you able to install DDBoost to one SQL Server / SQL Management Studio and link all your SQL Servers to it, so you can backup that way?  Wouldn't that cause a lot of network traffic?

**Comment by dmuegge** [comment]
@jnpetersen - Sorry it took me so long to reply. I'm fairly new to GitHub and just noticed this feature.

When using a linked server the process is generally setup so the DDBoost plug in and the Toolkit stored procedures are installed on each SQL server. This allows the servers to call stored procedures on each other via the linked server, but the processes are executed locally on each server. The backup and restore data flow is from each SQL server to and from the Data Domain. The linked servers would only pass control traffic.
