### ISSUE TITLE
Unable to populate catalog table

### ISSUE THREAD

**Issue by SMooner3** [dmuegge/ddb-sql-toolkit#3]
Can you please help me with populating the Catalog table.  I did not see a procedure or instructions on how to populate it.  This is a great toolkit

**Comment by dmuegge** [comment]
Thanks for the feedback.
The catalog table is populated via the DDBMABackup backup procedure upon successful backup.
The catalog table is created using the CreateDDBMASQLCatalogTable.sql script and the entries in the table can be managed/removed using the DDBMACatalog procedure. 

For your reference EMC just published a whitepaper I wrote on this subject which contains some detailed information on the subject. You can find it at the URL below.

[https://education.emc.com/content/_common/docs/ks_articles/2015KS_David-How_to_Boost_SQL_Server_Backups_with_Data_Domain.pdf](https://education.emc.com/content/_common/docs/ks_articles/2015KS_David-How_to_Boost_SQL_Server_Backups_with_Data_Domain.pdf)

Thanks, Dave
